<?php

namespace smpcl\ClassifieldBundle\Entity;

use Doctrine\ORM\EntityRepository;
use smpcl\ClassifieldBundle\Entity\Classifield;
/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    
    public function getClassififields($id) {
       $enabled_status = Classifield::STATUS_ENABLED;
       
        $dql = "SELECT c FROM smpcl\ClassifieldBundle\Entity\Classifield c
        WHERE c.category = {$id} AND c.status = '{$enabled_status}' ORDER BY c.published_at DESC";
        
        $query = $this->getEntityManager()->createQuery($dql);
        
        return $query->getResult();
    }
    
}