<?php

namespace smpcl\ClassifieldBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassifieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassifieldRepository extends EntityRepository {

    public function getClassifieldsByUser($user) {
        $dql = 'SELECT p FROM smpcl\ClassifieldBundle\Entity\Classifield p
        WHERE p.user = '.$user->getId().'   
        ORDER BY p.id DESC';

        $query = $this->getEntityManager()->createQuery($dql);
        //$query->setMaxResults($limit);

        return $query->getResult();
    }

}