<?php

namespace smpcl\ClassifieldBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassifieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassifieldRepository extends EntityRepository {

    public function getClassifieldsByUser($user) {
        return $this->findBy(array('user' => $user->getId()), array('id' => 'DESC'));
    }

}